# define functions
purl = Rscript -e "knitr::purl(input = '$(1)', \
                               output = '$(2)', \
                               quiet = TRUE, \
                               documentation = 0)"

knit2md = Rscript -e "knitr::knit2pandoc(input = '$(1)', \
                                         output = '$(2)', \
                                         tangle = FALSE, \
                                         encoding = 'UTF-8', \
                                         to = 'gfm')"

# generate all target R filenames
rfiles:=$(patsubst Rmd/%.Rmd,R/%-GEN.R,$(wildcard Rmd/*.Rmd))

# define target files to be built in standard make target "all"
all: $(rfiles) README.md

# build literate programming .Rmd source files
R/%-GEN.R: Rmd/%.Rmd
	$(call purl,$^,$@)
	sed -i "1i# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file \`$^\`.\n# See \`README.md#development\` for more information on the literature programming approach used applying the R Markdown format.\n" $@

# build README.md (always rebuild due to possibly changed external snippets in README.Rmd)
README.md: FORCE
	$(call knit2md,README.Rmd,README.md)
	if test -f README.gfm; then rm README.gfm; fi

FORCE:

